### ISSUE TITLE
The number of testing images?

### ISSUE THREAD

**Issue by happsky** [AAnoosheh/ComboGAN#1]
Thanks for you sharing your excellent codes. But a problem confused me.
The Alps Seasons dataset has 400 testing images, however, after doing testing, I obtained 1240 images in folder "image", why is not 400*5=2000 images generated rather 1240 images?

**Comment by AAnoosheh** [comment]
Hi happsky,

If you want to test on all images, please add testing flag `--serial_test`
This ensures the testing is done in sequential order from the folders.

By default it will select randomly from a folder (though folders are always alternated in order).
The problem you had is likely the images being re-used and overwriting each other.

Usually I don't test on all testing images but only a random subset so I don't "fine-tune/overfit" the network in a biased manner to what I see on the same images.

**Comment by happsky** [comment]
Thanks for your reply~
