### ISSUE TITLE
dataset is unavailable

### ISSUE THREAD

**Issue by syz825211943** [AAnoosheh/ComboGAN#10]
When i use .sh to download the dataset, the connection to the target url is always timed out. So how can i get the dataset?
![image](https://user-images.githubusercontent.com/26685037/55272904-1725c480-52ff-11e9-822a-6fb8995c2d1c.png)

**Comment by AAnoosheh** [comment]
Another issue talks about this same thing. I think the servers are just undergoing maintenance or something and keep going down from time to time. Just wait a few hours. 

Thanks
