### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by WeeshawChen** [AAnoosheh/ComboGAN#14]
There is something wrong when I try to test my own dataset, I've already trained my models and now I want to generate a new dataset so I write this command in my terminal :python test.py --phase test --name dimmer --dataroot ./datasets/stanfordcars/test0_day --n_domains 2 --which_epoch 195 --serial_test

**Comment by WeeshawChen** [comment]
and it just shows Created 2 Encoder-Decoder pairs
Number of parameters per Encoder: 5099143
Number of parameters per Decoder: 6565770
and nothing happened in my ./results/dimmer/test_195/images
Can you please tell me how to address my problem?

**Comment by AAnoosheh** [comment]
Because the dataloader is the same structure during train and test, you have to give it a dataroot with at least two folders starting with the word "test". (And it will test all N of these folders)

So for you I'm guessing it's just:
--dataroot ./datasets/stanfordcars/

Try that out and let me know.

**Comment by WeeshawChen** [comment]
emm, sadly it seems like nothing changed~ 
my dataset structure is like this:

- datasets
    - stanfordcars
         -test0_day
         -test1_night
         -train0_day
         -train1_night
so I write this command in my terminal:
`python test.py --phase test --name dimmer --dataroot ./datesets/stanfordcars/ --n_domains 2 --which_epoch 200 --serial_test`
And the problem is just as same as before~

**Comment by AAnoosheh** [comment]
May or may not be this, but ./datasets is misspelled in your command

**Comment by WeeshawChen** [comment]
oh my god.....it worked thanks to you. I am so sorry that I made a stupid typo problem, and I can't express how grateful I am! Thanks a lot!  :)
