### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by irukawang** [AAnoosheh/ComboGAN#3]
Can you share your datasets？ thanks

**Comment by AAnoosheh** [comment]
Hello, the images are available using the download script in the datasets directory.

**Comment by irukawang** [comment]
But I click url error， The requested URL /cvl/combogan/$FILE.zip was not found on this server.

**Comment by AAnoosheh** [comment]
You have the same problem as this guy:  https://github.com/AAnoosheh/ComboGAN/issues/2

There are multiple datasets so you need to specify which one you want. View the actual download_dataset.sh to see the argument options.

**Comment by irukawang** [comment]
thanks
