### ISSUE TITLE
Explanation for forward loss

### ISSUE THREAD

**Issue by RagMeh11** [AAnoosheh/ComboGAN#5]
Thanks for such a nice and clean code. Can you please explain what lambda_fwd is intended to do? 

https://github.com/AAnoosheh/ComboGAN/blob/master/models/combogan_model.py#L155

Thanks.

**Comment by AAnoosheh** [comment]
It's not documented explicitly I think, but it's just an L1 loss on a (downsampled 2x) image pre- and post-translation.

This is not desired in most cases, but, for example, when your domains are human faces of different ages, you don't want anything but the face region changed - and even then it should be changed minimally, such that the downsampled before/after images look nearly identical.

Thanks for your interest!
