### ISSUE TITLE
Objective function for four domains

### ISSUE THREAD

**Issue by Zeros12** [AAnoosheh/ComboGAN#6]
Hi, thanks for such a nice work.

In your paper, you have mentioned the objective of CycleGAN which is:
![screenshot from 2018-12-12 16-43-09](https://user-images.githubusercontent.com/30489050/49851570-3a4e6600-fe2d-11e8-8efd-8ff26459308a.png)

This is the objective for two domains only. As your work in ComboGAN can translate images from multiple domains, then if you have four domains, what will be the objective function for four domains?

**Comment by AAnoosheh** [comment]
Replying also with a screenshot from my paper:

![image](https://user-images.githubusercontent.com/5615503/49861986-7073f180-fdfd-11e8-8b59-ce8ddd05c520.png)

Cheers!
