### ISSUE TITLE
training hours 

### ISSUE THREAD

**Issue by Zeros12** [AAnoosheh/ComboGAN#7]
Hi, in your paper, you mentioned that "The fourteen painters dataset, for example, ran 1400 epochs in 220 hours on our nVidia Titan X GPU. Note that pairwise CycleGAN instead would have taken about 2860 hours, or four months."

How you calculated the training hours, i.e. 2860 hours for CycleGAN?

**Comment by AAnoosheh** [comment]
Hi,

It was sort of a back of the envelope calculation that assumes no parallel trainings.

[Time for 200eps of CycleGAN on 2 domains on our GPU] * (14 choose 2 domains) = approx. 2860 hrs

So just under 32 hours to train per regular CycleGAN, if I recall correctly.
