### ISSUE TITLE
Dataset Error 404: not found

### ISSUE THREAD

**Issue by bdseal** [AAnoosheh/ComboGAN#9]
Hi, thanks for your work! I have tried to download datasets by download_dataset.sh scripts and wget but failed. 
I have noticed  issue[3](https://github.com/AAnoosheh/ComboGAN/issues/3) and [2](https://github.com/AAnoosheh/ComboGAN/issues/2). But it still doesn't work.
![微信截图_20190326075338](https://user-images.githubusercontent.com/23097408/54961816-2b835d80-4f9d-11e9-9471-8c5575c9a2e8.png)

**Comment by AAnoosheh** [comment]
Hmmm.... Not sure cause it still works for me.

Try again now. Maybe servers were down temporarily.

**Comment by bdseal** [comment]
Works for me now. Thanks!
